services:
  backend:
    build:
      # Use the current scripts folder as build context (we run docker-compose from scripts/)
      context: .
      dockerfile: ./chatbot-backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # Veritabanı dosyasının kalıcı olmasını sağlar
      - ./chatbot-backend/workflow_state.db:/app/workflow_state.db
    environment:
      MCP_USER: "573527867"
      MCP_PASSWORD: "188129"
    networks:
      - chatbot-net

  frontend:
    build:
      context: ./chatbot-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - chatbot-net

networks:
  chatbot-net:
    driver: bridge
